title: SAATER AJE
description: Aje Saater David is detail-oriented with data analytics, graphics design, other Tech-organization skills, Python programming, SQL, desktop publishing expert.
theme: jekyll.theme.minimal
